# exported from PySB model 'None'

from pysb import Model, Monomer, Parameter, Expression, Compartment, Rule, Observable, Initial, MatchOnce, Annotation, ANY, WILD

Model()

Monomer(u'PPM1D', [u'activity'], {u'activity': [u'inactive', u'active']})
Monomer(u'TP53', [u'ub', u'activity'], {u'activity': [u'inactive', u'active'], u'ub': [u'n', u'y']})
Monomer(u'PROTEASE')
Monomer(u'ATM', [u'phospho', u'activity'], {u'phospho': [u'u', u'p'], u'activity': [u'inactive', u'active']})
Monomer(u'ARF')
Monomer(u'MDM2', [u'activity'], {u'activity': [u'inactive', u'active']})

Parameter(u'kf_a_autophos_1', 0.001)
Parameter(u'kf_m_t_ubiquitination_1', 1e-06)
Parameter(u'kf_at_act_1', 1e-06)
Parameter(u'kf_tp_act_1', 1e-06)
Parameter(u'kf_pt_act_1', 1e-05)
Parameter(u'kf_pa_act_1', 1e-06)
Parameter(u'kf_pp_act_1', 1e-06)
Parameter(u'kf_am_act_1', 1e-06)
Parameter(u'kf_m_deg_1', 2e-05)
Parameter(u'kf_t_deg_1', 2e-05)
Parameter(u'kf_t_synth_1', 0.002)
Parameter(u'kf_tm_synth_1', 0.2)
Parameter(u'PPM1D_0', 100.0)
Parameter(u'TP53_0', 100.0)
Parameter(u'PROTEASE_0', 100.0)
Parameter(u'ATM_0', 100.0)
Parameter(u'ARF_0', 100.0)
Parameter(u'MDM2_0', 100.0)

Observable('P53_active', TP53(activity='active'))

Rule(u'ATM_autophospho_ATM_phospho', ATM(phospho=u'u') >> ATM(phospho=u'p'), kf_a_autophos_1)
Rule(u'MDM2_ubiquitination_TP53_ub_1', MDM2(activity=u'active') + TP53(ub=u'n') >> MDM2(activity=u'active') + TP53(ub=u'y'), kf_m_t_ubiquitination_1)
Rule(u'ATM_phospho_activates_TP53_activity', ATM(phospho=(u'p', WILD)) + TP53(activity=u'inactive') >> ATM(phospho=(u'p', WILD)) + TP53(activity=u'active'), kf_at_act_1)
Rule(u'TP53_activates_PPM1D_activity', TP53() + PPM1D(activity=u'inactive') >> TP53() + PPM1D(activity=u'active'), kf_tp_act_1)
Rule(u'PPM1D_deactivates_TP53_activity', PPM1D() + TP53(activity=u'active') >> PPM1D() + TP53(activity=u'inactive'), kf_pt_act_1)
Rule(u'PPM1D_deactivates_ATM_activity', PPM1D() + ATM(activity=u'active') >> PPM1D() + ATM(activity=u'inactive'), kf_pa_act_1)
Rule(u'PROTEASE_deactivates_PPM1D_activity', PROTEASE() + PPM1D(activity=u'active') >> PROTEASE() + PPM1D(activity=u'inactive'), kf_pp_act_1)
Rule(u'ARF_deactivates_MDM2_activity', ARF() + MDM2(activity=u'active') >> ARF() + MDM2(activity=u'inactive'), kf_am_act_1)
Rule(u'MDM2_degraded', MDM2() >> None, kf_m_deg_1)
Rule(u'TP53_ub_degraded', TP53(ub=(u'y', WILD)) >> None, kf_t_deg_1)
Rule(u'TP53_synthesized', None >> TP53(ub=u'n', activity=u'inactive'), kf_t_synth_1)
Rule(u'TP53_synthesizes_MDM2', TP53() >> MDM2(activity=u'inactive') + TP53(), kf_tm_synth_1)

Initial(PPM1D(activity=u'inactive'), PPM1D_0)
Initial(TP53(ub=u'n', activity=u'inactive'), TP53_0)
Initial(PROTEASE(), PROTEASE_0)
Initial(ATM(phospho=u'u', activity=u'inactive'), ATM_0)
Initial(ARF(), ARF_0)
Initial(MDM2(activity=u'inactive'), MDM2_0)

Annotation(PPM1D, u'http://identifiers.org/hgnc/HGNC:9277', u'is')
Annotation(PPM1D, u'http://identifiers.org/uniprot/O15297', u'is')
Annotation(TP53, u'http://identifiers.org/hgnc/HGNC:11998', u'is')
Annotation(TP53, u'http://identifiers.org/uniprot/P04637', u'is')
Annotation(ATM, u'http://identifiers.org/uniprot/Q13315', u'is')
Annotation(ATM, u'http://identifiers.org/hgnc/HGNC:795', u'is')
Annotation(MDM2, u'http://identifiers.org/uniprot/Q00987', u'is')
Annotation(MDM2, u'http://identifiers.org/hgnc/HGNC:6973', u'is')
Annotation(ATM_autophospho_ATM_phospho, u'ATM', u'rule_has_subject')
Annotation(ATM_autophospho_ATM_phospho, u'ATM', u'rule_has_object')
Annotation(MDM2_ubiquitination_TP53_ub_1, u'MDM2', u'rule_has_subject')
Annotation(MDM2_ubiquitination_TP53_ub_1, u'TP53', u'rule_has_object')
Annotation(ATM_phospho_activates_TP53_activity, u'ATM', u'rule_has_subject')
Annotation(ATM_phospho_activates_TP53_activity, u'TP53', u'rule_has_object')
Annotation(TP53_activates_PPM1D_activity, u'TP53', u'rule_has_subject')
Annotation(TP53_activates_PPM1D_activity, u'PPM1D', u'rule_has_object')
Annotation(PPM1D_deactivates_TP53_activity, u'PPM1D', u'rule_has_subject')
Annotation(PPM1D_deactivates_TP53_activity, u'TP53', u'rule_has_object')
Annotation(PPM1D_deactivates_ATM_activity, u'PPM1D', u'rule_has_subject')
Annotation(PPM1D_deactivates_ATM_activity, u'ATM', u'rule_has_object')
Annotation(PROTEASE_deactivates_PPM1D_activity, u'PROTEASE', u'rule_has_subject')
Annotation(PROTEASE_deactivates_PPM1D_activity, u'PPM1D', u'rule_has_object')
Annotation(ARF_deactivates_MDM2_activity, u'ARF', u'rule_has_subject')
Annotation(ARF_deactivates_MDM2_activity, u'MDM2', u'rule_has_object')

